package com.topgroup.capa.base.view.screen;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.topgroup.capa.base.view.bean.ProductoFormPanel;
import com.topgroup.capa.base.view.bean.ProductoSearchPanel;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

@Component
@Scope("prototype")
public class PracticeScreen extends CustomComponent {

	private static final long serialVersionUID = -4479639018984308437L;
	
	private VerticalLayout mainLayout;
	
	@Autowired
	ProductoSearchPanel productoSearchPanel;// = new ProductoSearchPanel();
	
	@Autowired
	ProductoFormPanel productoFormPanel;// = new ProductoFormPanel();
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PracticeScreen() {
		System.out.println("Pase por PracticeScreen 1");
		buildMainLayout();
		System.out.println("Pase por PracticeScreen 2");
		setCompositionRoot(mainLayout);
		System.out.println("Fin de pase por PracticeScreen 3");

	}
	
	@PostConstruct
	protected void init() {
		System.out.println("PASE POR ACAAAAAAAA 4");
		mainLayout.addComponent(productoSearchPanel);
		System.out.println("PASE POR ACAAAAAAAA 5");
		mainLayout.addComponent(productoFormPanel);
		System.out.println("PASE POR ACAAAAAAAA 6");
	}

	@AutoGenerated
	private void buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		Label label = new Label("Práctica de Commons- Vaadin");
		label.addStyleName("title");
		
	}


}
